name: check jobs

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:    # Allow manual trigger

jobs:
  check-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        JOB_URL: ${{ secrets.JOB_URL }}
        JOB_KEYWORDS: ${{ secrets.JOB_KEYWORDS }}
      run: python main.py
